version: 2.1
# orbs - reusable packages for use 
# in yml files, tabs are important, so must align and tab properly
orbs: 
  node: circleci/node@5.0.1
  docker: circleci/docker@2.1.4
# jobs - set of instructions / functions 
jobs: 
  build: #job name 
    docker: #environment
      - image: cimg/node:16.10
    steps: 
      - checkout 
      - node/install-packages: 
          pkg-manager: npm 
      - run: |
          echo "Installing dependencies..."
          npm install 
  
  test: 
    docker: 
      - image: cimg/node:16.10
    steps: 
      - checkout
      - node/install-packages: 
          pkg-manager: npm 
      - run: |
          echo "Running tests..."
          npm run test
  
  publish:  #just a naming convention, also known as build-and-push
    executor: docker/docker #define the execution environment in which the steps of a job will run
    steps: 
      - setup_remote_docker
      - checkout
      - docker/check 
      - docker/build: #build the image 
          image: xinyu98/education-space
      - docker/push: 
          image: xinyu98/education-space


# workflow - defines what sequence the jobs will run
workflows: 
  simple_workflow: #workflow name 
    jobs: 
      - build #Step 1 
      - test:  #Step 2
          requires: 
            - build #test has a requirement that build must finish before we can go to the build job 
      - publish: 
          requires: 
            - test #publish requires test to finish 
